/*
 * Protocol between hex server and remote AI workers.
 *
 * Source of truth: a copy lives in hex-ai-distributed (src/shared/protocol.ts),
 * keep both in sync when changing this file.
 *
 * Workers pull jobs with an api key:
 *
 *  Header: Authorization: Bearer <key>
 *
 *  POST /api/ai-workers/jobs/next              { types, workerId }                    => 200 ReservedJob | 204 no job yet
 *  POST /api/ai-workers/jobs/:jobId/heartbeat  { workerId, token }                    => 204 | 409 job not owned anymore
 *  POST /api/ai-workers/jobs/:jobId/result     { workerId, token, result }            => 204 | 409 | 400 invalid result
 *  POST /api/ai-workers/jobs/:jobId/fail       { workerId, token, error, retryable }  => 204 | 409
 *
 *  401: invalid or revoked key, worker should stop.
 *
 * types: job types the worker processes, see AI_JOB_TYPES.
 * workerId: random id generated by the worker process on start.
 */

/**
 * Engines run by workers. A worker runs one engine, and processes job types of this engine.
 */
export const ENGINES = ['katahex', 'mohex', 'davies'] as const;

export type Engine = typeof ENGINES[number];

export const isEngine = (engine: unknown): engine is Engine =>
    ENGINES.includes(engine as Engine)
;

/**
 * While processing a job, worker must send a heartbeat at this interval.
 */
export const HEARTBEAT_MS = 10_000;

/**
 * Each heartbeat extends job lock for this duration.
 * If worker stops sending heartbeats, job is given to another worker after lock expires.
 */
export const LOCK_MS = 30_000;

/**
 * How long a worker request to get next job is held when there is no job,
 * before responding 204. Worker then directly sends a new request.
 */
export const LONG_POLL_MS = 25_000;

/*
 * Tasks
 */

export type GameInput = {
    size: number;

    /**
     * All played moves, i.e "a1 swap-pieces b2 pass ...".
     * Next move will be calculated.
     */
    movesHistory: string;

    currentPlayer: 'black' | 'white';

    /**
     * Whether the swap-pieces move is allowed or not in this game.
     */
    swapRule: boolean;
};

export type KatahexMoveInput = {
    game: GameInput;
};

export type MohexMoveInput = {
    game: GameInput;

    /**
     * Limit Mohex power by limiting simulation games (param "max_games").
     */
    maxGames: number;
};

export type DaviesMoveInput = {
    game: GameInput;

    level: number;
};

/**
 * A move like "f6", or "swap-pieces", "resign".
 */
export type MoveOutput = string;
export type AnalyzeMoveInput = {
    /**
     * Index of the analyzed move, 0 for the first move.
     */
    moveIndex: number;

    /**
     * Move played by player.
     */
    move: string;

    /**
     * Player who played "move".
     */
    color: 'black' | 'white';

    /**
     * If this move is the last of the game,
     * winRate should be calculated for played move,
     * and best move if different from played move.
     */
    isLastMoveOfGame: boolean;

    /**
     * Moves played before current move, excluding current move.
     * Empty for moveIndex 0.
     */
    movesHistory: string;

    size: number;
};

export type MoveAndValue = {
    move: string;

    /**
     * Value of the move from katahex model.
     * Relative to other moves of same position.
     */
    value: number;

    /**
     * White win rate of position after this move is played.
     */
    whiteWin?: number;
};

export type AnalyzeMoveOutput = {
    /**
     * moveIndex from AnalyzeMoveInput.
     */
    moveIndex: number;

    /**
     * White win rate before move played.
     */
    whiteWin: number;

    /**
     * color from AnalyzeMoveInput.
     */
    color: 'black' | 'white';

    /**
     * move from AnalyzeMoveInput, with its value.
     */
    move: MoveAndValue;

    /**
     * Alternative best moves and their values.
     */
    bestMoves: MoveAndValue[];
};

export type AnalyzePositionInput = {
    color: 'black' | 'white';
    size: number;
    white: string;
    black: string;
};

export type AnalyzePositionOutput = {
    whiteWin: number;
    policy: number[][];
};

/**
 * Input and output of each job type.
 */
type AiJobTypeDefinitions = {
    /**
     * Katahex move from raw neural network output, without tree search. Fast.
     */
    'katahex-intuition-move': { input: KatahexMoveInput, output: MoveOutput };

    /**
     * Katahex move with tree search (MCTS). Stronger, requires more computing power.
     */
    'katahex-mcts-move': { input: KatahexMoveInput, output: MoveOutput };

    'mohex': { input: MohexMoveInput, output: MoveOutput };

    'davies': { input: DaviesMoveInput, output: MoveOutput };

    /**
     * Win rate and policy of a position, from raw neural network output. Used by Hexplorer.
     */
    'katahex-intuition-analyze-position': { input: AnalyzePositionInput, output: AnalyzePositionOutput };

    /**
     * Analyze of a move of a game, from raw neural network output.
     * A game analyze is split in one job per move.
     */
    'katahex-intuition-analyze-move': { input: AnalyzeMoveInput, output: AnalyzeMoveOutput };

    /**
     * Same as katahex-intuition-analyze-position, with tree search. Not yet used.
     */
    'katahex-mcts-analyze-position': { input: AnalyzePositionInput, output: AnalyzePositionOutput };

    /**
     * Same as katahex-intuition-analyze-move, with tree search. Not yet used.
     */
    'katahex-mcts-analyze-move': { input: AnalyzeMoveInput, output: AnalyzeMoveOutput };
};

export type AiJobType = keyof AiJobTypeDefinitions;

/**
 * All job types, one queue per job type.
 *
 * Ordered by priority: a worker processing multiple job types
 * gets jobs of first types first (bot moves, where a player waits, before analyzes).
 */
export const AI_JOB_TYPES = [
    'katahex-intuition-move',
    'katahex-mcts-move',
    'mohex',
    'davies',
    'katahex-intuition-analyze-position',
    'katahex-mcts-analyze-position',
    'katahex-intuition-analyze-move',
    'katahex-mcts-analyze-move',
] as const satisfies readonly AiJobType[];

/**
 * Job types requiring more computing power.
 * Workers process them only when explicitly listed in their AI_JOB_TYPES env var.
 */
export const OPT_IN_AI_JOB_TYPES: readonly AiJobType[] = [
    'katahex-mcts-move',
    'katahex-mcts-analyze-position',
    'katahex-mcts-analyze-move',
];

export const isAiJobType = (type: unknown): type is AiJobType =>
    (AI_JOB_TYPES as readonly unknown[]).includes(type)
;

/**
 * Engine required to process a job type.
 */
export const getAiJobTypeEngine = (type: AiJobType): Engine =>
    ENGINES.find(engine => type === engine || type.startsWith(engine + '-'))!
;

/**
 * Job types a worker of this engine can process.
 */
export const getEngineAiJobTypes = (engine: Engine): AiJobType[] =>
    AI_JOB_TYPES.filter(type => getAiJobTypeEngine(type) === engine)
;

/**
 * Job types a worker of this engine processes when AI_JOB_TYPES is not set:
 * all job types of the engine, except opt-in ones.
 */
export const getEngineDefaultAiJobTypes = (engine: Engine): AiJobType[] =>
    getEngineAiJobTypes(engine).filter(type => !OPT_IN_AI_JOB_TYPES.includes(type))
;

export type AiTask = {
    [T in AiJobType]: {
        type: T;
        data: AiJobTypeDefinitions[T]['input'];
    };
}[AiJobType];

/**
 * Tasks computing a bot move.
 */
export type MoveTask = Extract<AiTask, { data: { game: GameInput } }>;

export type AiTaskOutput<T extends AiJobType> = AiJobTypeDefinitions[T]['output'];

/**
 * Sent to worker when it gets a job.
 * Worker must send back jobId and token with heartbeats and result.
 */
export type ReservedJob = {
    jobId: string;
    token: string;
    task: AiTask;
};
