# Accept or refuse an undo request. Requires authentication.

@gamePublicId=00000000-0000-0000-0000-000000000000

POST /api/games/{{ gamePublicId }}/answer-undo
Content-Type: application/json

{
    "accept": true
}
