import { MigrationInterface, QueryRunner } from 'typeorm';

export class Init0000000000001 implements MigrationInterface {
    name = 'Init0000000000001';

    async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`chat_message\` (\`id\` int NOT NULL AUTO_INCREMENT, \`publicId\` char(36) NOT NULL, \`playerId\` int NULL, \`content\` varchar(1000) NOT NULL, \`contentTranslationKey\` varchar(64) NULL, \`translationParameters\` json NULL, \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`shadowDeleted\` tinyint NOT NULL DEFAULT 0, \`deletedByModeration\` tinyint NOT NULL DEFAULT 0, \`hostedGameId\` int NOT NULL, INDEX \`IDX_1494ddf57db06eb4a8fb13d95e\` (\`createdAt\` DESC), UNIQUE INDEX \`IDX_bb865ed2d1270259065314ef35\` (\`publicId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hosted_game_to_player\` (\`hostedGameId\` int NOT NULL, \`playerId\` int NOT NULL, \`order\` smallint NOT NULL, PRIMARY KEY (\`hostedGameId\`, \`order\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_participant\` (\`tournamentId\` int NOT NULL, \`playerId\` int NOT NULL, \`rank\` int NULL, \`score\` int NOT NULL DEFAULT '0', \`tiebreak\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`tournamentId\`, \`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_subscription\` (\`tournamentId\` int NOT NULL, \`playerId\` int NOT NULL, \`subscribedAt\` datetime NULL, \`checkedIn\` datetime NULL, PRIMARY KEY (\`tournamentId\`, \`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`type\` varchar(255) NOT NULL, \`parameters\` json NOT NULL, \`date\` datetime NOT NULL, \`tournamentId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_admin\` (\`tournamentId\` int NOT NULL, \`playerId\` int NOT NULL, PRIMARY KEY (\`tournamentId\`, \`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament\` (\`id\` int NOT NULL AUTO_INCREMENT, \`state\` varchar(16) NOT NULL, \`publicId\` char(36) NOT NULL, \`title\` varchar(64) NOT NULL, \`description\` longtext NULL, \`slug\` varchar(64) NOT NULL, \`stage1Format\` varchar(32) NOT NULL, \`stage1Rounds\` int NULL, \`stage2Format\` varchar(32) NULL, \`consolation\` tinyint NOT NULL DEFAULT 1, \`seedingMethod\` varchar(16) NOT NULL DEFAULT 'rating_random', \`ranked\` tinyint NOT NULL DEFAULT 1, \`boardsize\` smallint NOT NULL DEFAULT '11', \`timeControlType\` json NOT NULL, \`explorationAllowed\` tinyint NOT NULL DEFAULT 1, \`accountRequired\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`startOfficialAt\` datetime NOT NULL, \`checkInOpenOffsetSeconds\` int NOT NULL, \`startDelayInSeconds\` int NOT NULL DEFAULT '0', \`startedAt\` datetime NULL, \`endedAt\` datetime NULL, \`canceledAt\` datetime NULL, \`cancelReason\` varchar(255) NULL, \`featuredFromInSeconds\` int NOT NULL DEFAULT '0', \`engineData\` json NULL, \`organizerId\` int NOT NULL, UNIQUE INDEX \`IDX_4839ffb50981dfa7f67c270b77\` (\`publicId\`), UNIQUE INDEX \`IDX_698317abb506538c31157f1f8d\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_match\` (\`id\` int NOT NULL AUTO_INCREMENT, \`state\` varchar(16) NOT NULL, \`group\` int NOT NULL DEFAULT '0', \`round\` int NOT NULL, \`number\` int NOT NULL, \`label\` varchar(31) NULL, \`bye\` tinyint NOT NULL DEFAULT 0, \`winnerPath\` varchar(8) NULL, \`loserPath\` varchar(8) NULL, \`tournamentId\` int NULL, \`hostedGameId\` int NULL, \`player1Id\` int NULL, \`player2Id\` int NULL, UNIQUE INDEX \`IDX_2b9bc4824bb07421f07185f7bc\` (\`tournamentId\`, \`group\`, \`round\`, \`number\`), UNIQUE INDEX \`REL_c274da5202ba2bfed1b709bd91\` (\`hostedGameId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hosted_game\` (\`id\` int NOT NULL AUTO_INCREMENT, \`publicId\` char(36) NOT NULL, \`state\` varchar(15) NOT NULL, \`ranked\` tinyint NOT NULL, \`boardsize\` smallint NOT NULL, \`firstPlayer\` smallint NULL, \`swapRule\` tinyint NOT NULL, \`opponentType\` varchar(15) NOT NULL, \`opponentPublicId\` char(36) NULL, \`timeControlType\` json NOT NULL, \`timeControl\` json NOT NULL, \`explorationAllowed\` tinyint NOT NULL DEFAULT 1, \`moves\` text NOT NULL, \`moveTimestamps\` longtext NOT NULL, \`currentPlayerIndex\` smallint NOT NULL DEFAULT '0', \`winner\` smallint NULL, \`outcome\` varchar(15) NULL, \`undoRequest\` smallint NULL, \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`startedAt\` datetime(3) NULL, \`lastMoveAt\` datetime(3) NULL, \`endedAt\` datetime(3) NULL, \`adminComments\` text NULL, \`hostId\` int NULL, \`rematchId\` int NULL, \`rematchedFromId\` int NULL, INDEX \`index_opponentType_endedAt_desc\` (\`opponentType\`, \`endedAt\` DESC), INDEX \`index_opponentType_endedAt\` (\`opponentType\`, \`endedAt\`), INDEX \`index_ranked_opponentType_endedAt_desc\` (\`ranked\`, \`opponentType\`, \`endedAt\` DESC), INDEX \`index_ranked_opponentType_endedAt\` (\`ranked\`, \`opponentType\`, \`endedAt\`), INDEX \`index_state_ranked_opponentType_endedAt_desc\` (\`state\`, \`ranked\`, \`opponentType\`, \`endedAt\` DESC), INDEX \`index_state_ranked_opponentType_endedAt\` (\`state\`, \`ranked\`, \`opponentType\`, \`endedAt\`), INDEX \`index_state_opponentType_endedAt_desc\` (\`state\`, \`opponentType\`, \`endedAt\` DESC), INDEX \`index_state_opponentType_endedAt\` (\`state\`, \`opponentType\`, \`endedAt\`), INDEX \`index_state_endedAt_desc\` (\`state\`, \`endedAt\` DESC), INDEX \`index_state_endedAt\` (\`state\`, \`endedAt\`), INDEX \`index_endedAt_desc\` (\`endedAt\` DESC), INDEX \`index_endedAt\` (\`endedAt\`), INDEX \`IDX_0ba44d40b3239783f505eeb25d\` (\`state\`, \`boardsize\`), INDEX \`IDX_7a3457cfa4a21186667d094da8\` (\`state\`, \`opponentType\`, \`ranked\`), UNIQUE INDEX \`IDX_f76de6ed10d8423f5282f4e022\` (\`publicId\`), UNIQUE INDEX \`REL_b1e0077ad74acda2ff6850016d\` (\`rematchId\`), UNIQUE INDEX \`REL_9bf2411e82c38cfd8af4f4c641\` (\`rematchedFromId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rating\` (\`id\` int NOT NULL AUTO_INCREMENT, \`category\` varchar(255) NOT NULL, \`createdAt\` datetime NOT NULL, \`rating\` float NOT NULL, \`deviation\` float NOT NULL, \`volatility\` float NOT NULL, \`ratingChange\` float NULL, \`playerId\` int NULL, INDEX \`IDX_b5f6a27c596dd94c726d6fcbb3\` (\`playerId\`, \`category\`, \`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player\` (\`id\` int NOT NULL AUTO_INCREMENT, \`pseudo\` varchar(34) NOT NULL, \`publicId\` char(36) NOT NULL, \`isGuest\` tinyint NOT NULL DEFAULT 0, \`isBot\` tinyint NOT NULL DEFAULT 0, \`slug\` varchar(34) NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`registeredAt\` datetime NULL, \`password\` char(60) NULL, \`shadowBanned\` tinyint NOT NULL DEFAULT 0, \`avatarPath\` varchar(255) NULL, \`avatarThumbnailPath\` varchar(255) NULL, \`avatarUpdatedAt\` datetime NULL, \`countryFlag\` varchar(8) NULL, \`currentRatingId\` int NULL, INDEX \`IDX_0e28654c29f71f06b98759dada\` (\`avatarUpdatedAt\`), INDEX \`IDX_241146be1657c624807b4cf869\` (\`isGuest\`, \`isBot\`, \`pseudo\`), UNIQUE INDEX \`IDX_6ee4bd7846a1ef85af5f6134ae\` (\`pseudo\`), UNIQUE INDEX \`IDX_a457ce2bf3dff68e40d8ed0ea8\` (\`publicId\`), UNIQUE INDEX \`IDX_fd3768c309e99f68d3a1cbadc7\` (\`slug\`), UNIQUE INDEX \`REL_4ad11722d1a822cb14f277340d\` (\`currentRatingId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ai_config\` (\`playerId\` int NOT NULL, \`engine\` varchar(191) NOT NULL, \`label\` varchar(32) NOT NULL, \`description\` varchar(64) NULL, \`relativeLevel\` smallint NULL, \`boardsizeMin\` smallint NULL, \`boardsizeMax\` smallint NULL, \`requireMorePower\` tinyint NOT NULL DEFAULT 0, \`isRemote\` tinyint NOT NULL DEFAULT 0, \`config\` json NOT NULL, \`order\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`channel_chat_message\` (\`id\` int NOT NULL AUTO_INCREMENT, \`publicId\` char(36) NOT NULL, \`playerId\` int NULL, \`content\` varchar(1000) NOT NULL, \`contentTranslationKey\` varchar(64) NULL, \`translationParameters\` json NULL, \`createdAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`shadowDeleted\` tinyint NOT NULL DEFAULT 0, \`deletedByModeration\` tinyint NOT NULL DEFAULT 0, \`channelId\` int NOT NULL, INDEX \`IDX_e1f0bf78f736fd2d332252fb32\` (\`createdAt\` DESC), UNIQUE INDEX \`IDX_304b2f9ce4b54361694f08e939\` (\`publicId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`channel\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_800e6da7e4c30fbb0653ba7bb6\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conditional_moves\` (\`hostedGameId\` int NOT NULL, \`playerId\` int NOT NULL, \`tree\` json NOT NULL, \`unplayedLines\` json NOT NULL, PRIMARY KEY (\`hostedGameId\`, \`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`game_analyze\` (\`hostedGameId\` int NOT NULL, \`analyze\` json NULL, \`startedAt\` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`endedAt\` datetime(3) NULL, PRIMARY KEY (\`hostedGameId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player_moderation_action\` (\`id\` int NOT NULL AUTO_INCREMENT, \`publicId\` char(36) NOT NULL, \`reason\` varchar(64) NULL, \`reasonDetails\` varchar(255) NULL, \`chatBlockedUntil\` datetime NULL, \`avatarBlockedUntil\` datetime NULL, \`acknowledgedAt\` datetime NULL, \`createdAt\` datetime NOT NULL, \`playerId\` int NULL, UNIQUE INDEX \`IDX_733a724427bf9b9b24d43e1539\` (\`publicId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player_notification\` (\`id\` int NOT NULL AUTO_INCREMENT, \`publicId\` char(36) NOT NULL, \`playerId\` int NOT NULL, \`type\` varchar(64) NOT NULL, \`parameters\` json NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`hostedGameId\` int NULL, UNIQUE INDEX \`IDX_0e4299931e18a9f324a4f87b3f\` (\`publicId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player_push_subscription\` (\`id\` int NOT NULL AUTO_INCREMENT, \`playerId\` int NOT NULL, \`endpoint\` varchar(512) NOT NULL, \`expirationTime\` int NULL, \`keys\` json NOT NULL, \`createdAt\` datetime NOT NULL, INDEX \`IDX_c3540736ec9e18b0921ff57663\` (\`endpoint\`), UNIQUE INDEX \`IDX_7c969e1d02d0de0392f3562e29\` (\`playerId\`, \`endpoint\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player_settings\` (\`playerId\` int NOT NULL, \`moveSettingsBlitz\` int NOT NULL DEFAULT '1', \`moveSettingsNormal\` int NOT NULL DEFAULT '1', \`moveSettingsCorrespondence\` int NOT NULL DEFAULT '2', \`orientationLandscape\` smallint NOT NULL DEFAULT '11', \`orientationPortrait\` smallint NOT NULL DEFAULT '9', \`showCoords\` tinyint NOT NULL DEFAULT 0, \`show44dots\` tinyint NOT NULL DEFAULT 0, \`boardShadingPattern\` varchar(64) NULL, \`boardShadingPatternOption\` varchar(255) NULL, \`boardShadingPatternIntensity\` float NOT NULL DEFAULT '1', \`showTutorial\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tournament_banned_player\` (\`tournamentId\` int NOT NULL, \`playerId\` int NOT NULL, PRIMARY KEY (\`tournamentId\`, \`playerId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rating_games_hosted_game\` (\`ratingId\` int NOT NULL, \`hostedGameId\` int NOT NULL, INDEX \`IDX_870f3e487e4342542fe7f959d2\` (\`ratingId\`), INDEX \`IDX_8a004a11c3f59b65cb9af2f58e\` (\`hostedGameId\`), PRIMARY KEY (\`ratingId\`, \`hostedGameId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player_moderation_action_chat_message\` (\`playerModerationActionId\` int NOT NULL, \`chatMessageId\` int NOT NULL, INDEX \`IDX_6ea10243a0f603c2e578c15082\` (\`playerModerationActionId\`), INDEX \`IDX_2919df3d450d056338c5d86e93\` (\`chatMessageId\`), PRIMARY KEY (\`playerModerationActionId\`, \`chatMessageId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`player_moderation_action_channel_chat_message\` (\`playerModerationActionId\` int NOT NULL, \`channelChatMessageId\` int NOT NULL, INDEX \`IDX_32046a0dd10be92520342f800e\` (\`playerModerationActionId\`), INDEX \`IDX_187aa9ff1431c29528960322b0\` (\`channelChatMessageId\`), PRIMARY KEY (\`playerModerationActionId\`, \`channelChatMessageId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`chat_message\` ADD CONSTRAINT \`FK_066efba3e9ebaaf2a9363b44bef\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_message\` ADD CONSTRAINT \`FK_c11c5541b19938027069b21ef66\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hosted_game_to_player\` ADD CONSTRAINT \`FK_fdf42b21f9f53fc1591693f3dab\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hosted_game_to_player\` ADD CONSTRAINT \`FK_a8b097c56ee69fdddf730e7cf78\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_participant\` ADD CONSTRAINT \`FK_ff34ec6606707ba26db17e16cee\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_participant\` ADD CONSTRAINT \`FK_dc4bf5986dc2754e8fa6141de1e\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_subscription\` ADD CONSTRAINT \`FK_24a012d4472711117179de117a3\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_subscription\` ADD CONSTRAINT \`FK_740a292db70568125e804ec81fe\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_history\` ADD CONSTRAINT \`FK_5260cc7b38cb3dcf6cd1599a038\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_admin\` ADD CONSTRAINT \`FK_cb6125b61aa3cf2fd9176cab63f\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_admin\` ADD CONSTRAINT \`FK_a3fafe30c4529ae594db838c194\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament\` ADD CONSTRAINT \`FK_9ddfd4f20c2d0fd731bbd681ae7\` FOREIGN KEY (\`organizerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` ADD CONSTRAINT \`FK_798f3a43f03fef1d3b716b49cbf\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` ADD CONSTRAINT \`FK_c274da5202ba2bfed1b709bd91b\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` ADD CONSTRAINT \`FK_dadc0fbc5a781e12238d18c2bf5\` FOREIGN KEY (\`player1Id\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` ADD CONSTRAINT \`FK_4e69882dfa491440fd16f8de41d\` FOREIGN KEY (\`player2Id\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hosted_game\` ADD CONSTRAINT \`FK_8485625a8b08f4e466a677c0ff1\` FOREIGN KEY (\`hostId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hosted_game\` ADD CONSTRAINT \`FK_b1e0077ad74acda2ff6850016db\` FOREIGN KEY (\`rematchId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hosted_game\` ADD CONSTRAINT \`FK_9bf2411e82c38cfd8af4f4c6419\` FOREIGN KEY (\`rematchedFromId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating\` ADD CONSTRAINT \`FK_7b7b67ede0cccc5f041b2f976a2\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player\` ADD CONSTRAINT \`FK_4ad11722d1a822cb14f277340d2\` FOREIGN KEY (\`currentRatingId\`) REFERENCES \`rating\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ai_config\` ADD CONSTRAINT \`FK_39a4da227a03e4dbd5acf681a0f\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`channel_chat_message\` ADD CONSTRAINT \`FK_b1133be5f324d3948f216c85984\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`channel_chat_message\` ADD CONSTRAINT \`FK_fb86d7dff98c0bd012d05a957c4\` FOREIGN KEY (\`channelId\`) REFERENCES \`channel\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conditional_moves\` ADD CONSTRAINT \`FK_59ba669f0f2f106699368e147cb\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conditional_moves\` ADD CONSTRAINT \`FK_84056359851e8b588fbba89e2ea\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_analyze\` ADD CONSTRAINT \`FK_0b5fa1ca52d143efd83c509ae79\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action\` ADD CONSTRAINT \`FK_98a917e972832562d85b59fb683\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_notification\` ADD CONSTRAINT \`FK_358aa08af0037ad39f7b3e6a530\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_notification\` ADD CONSTRAINT \`FK_a579029a5b14be3e6e13a8616ea\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_push_subscription\` ADD CONSTRAINT \`FK_cb3c3eadca376bb48aeeee9be4e\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_settings\` ADD CONSTRAINT \`FK_43ccfbeeabe06a10a1548d7b7ec\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_banned_player\` ADD CONSTRAINT \`FK_55743b3b80808e5b0b0a41e829f\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournament\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tournament_banned_player\` ADD CONSTRAINT \`FK_86b25f7c30ebc6078a627458ab1\` FOREIGN KEY (\`playerId\`) REFERENCES \`player\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_games_hosted_game\` ADD CONSTRAINT \`FK_870f3e487e4342542fe7f959d27\` FOREIGN KEY (\`ratingId\`) REFERENCES \`rating\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`rating_games_hosted_game\` ADD CONSTRAINT \`FK_8a004a11c3f59b65cb9af2f58ea\` FOREIGN KEY (\`hostedGameId\`) REFERENCES \`hosted_game\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_chat_message\` ADD CONSTRAINT \`FK_6ea10243a0f603c2e578c150824\` FOREIGN KEY (\`playerModerationActionId\`) REFERENCES \`player_moderation_action\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_chat_message\` ADD CONSTRAINT \`FK_2919df3d450d056338c5d86e93f\` FOREIGN KEY (\`chatMessageId\`) REFERENCES \`chat_message\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_channel_chat_message\` ADD CONSTRAINT \`FK_32046a0dd10be92520342f800e9\` FOREIGN KEY (\`playerModerationActionId\`) REFERENCES \`player_moderation_action\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_channel_chat_message\` ADD CONSTRAINT \`FK_187aa9ff1431c29528960322b09\` FOREIGN KEY (\`channelChatMessageId\`) REFERENCES \`channel_chat_message\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_channel_chat_message\` DROP FOREIGN KEY \`FK_187aa9ff1431c29528960322b09\``);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_channel_chat_message\` DROP FOREIGN KEY \`FK_32046a0dd10be92520342f800e9\``);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_chat_message\` DROP FOREIGN KEY \`FK_2919df3d450d056338c5d86e93f\``);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action_chat_message\` DROP FOREIGN KEY \`FK_6ea10243a0f603c2e578c150824\``);
        await queryRunner.query(`ALTER TABLE \`rating_games_hosted_game\` DROP FOREIGN KEY \`FK_8a004a11c3f59b65cb9af2f58ea\``);
        await queryRunner.query(`ALTER TABLE \`rating_games_hosted_game\` DROP FOREIGN KEY \`FK_870f3e487e4342542fe7f959d27\``);
        await queryRunner.query(`ALTER TABLE \`tournament_banned_player\` DROP FOREIGN KEY \`FK_86b25f7c30ebc6078a627458ab1\``);
        await queryRunner.query(`ALTER TABLE \`tournament_banned_player\` DROP FOREIGN KEY \`FK_55743b3b80808e5b0b0a41e829f\``);
        await queryRunner.query(`ALTER TABLE \`player_settings\` DROP FOREIGN KEY \`FK_43ccfbeeabe06a10a1548d7b7ec\``);
        await queryRunner.query(`ALTER TABLE \`player_push_subscription\` DROP FOREIGN KEY \`FK_cb3c3eadca376bb48aeeee9be4e\``);
        await queryRunner.query(`ALTER TABLE \`player_notification\` DROP FOREIGN KEY \`FK_a579029a5b14be3e6e13a8616ea\``);
        await queryRunner.query(`ALTER TABLE \`player_notification\` DROP FOREIGN KEY \`FK_358aa08af0037ad39f7b3e6a530\``);
        await queryRunner.query(`ALTER TABLE \`player_moderation_action\` DROP FOREIGN KEY \`FK_98a917e972832562d85b59fb683\``);
        await queryRunner.query(`ALTER TABLE \`game_analyze\` DROP FOREIGN KEY \`FK_0b5fa1ca52d143efd83c509ae79\``);
        await queryRunner.query(`ALTER TABLE \`conditional_moves\` DROP FOREIGN KEY \`FK_84056359851e8b588fbba89e2ea\``);
        await queryRunner.query(`ALTER TABLE \`conditional_moves\` DROP FOREIGN KEY \`FK_59ba669f0f2f106699368e147cb\``);
        await queryRunner.query(`ALTER TABLE \`channel_chat_message\` DROP FOREIGN KEY \`FK_fb86d7dff98c0bd012d05a957c4\``);
        await queryRunner.query(`ALTER TABLE \`channel_chat_message\` DROP FOREIGN KEY \`FK_b1133be5f324d3948f216c85984\``);
        await queryRunner.query(`ALTER TABLE \`ai_config\` DROP FOREIGN KEY \`FK_39a4da227a03e4dbd5acf681a0f\``);
        await queryRunner.query(`ALTER TABLE \`player\` DROP FOREIGN KEY \`FK_4ad11722d1a822cb14f277340d2\``);
        await queryRunner.query(`ALTER TABLE \`rating\` DROP FOREIGN KEY \`FK_7b7b67ede0cccc5f041b2f976a2\``);
        await queryRunner.query(`ALTER TABLE \`hosted_game\` DROP FOREIGN KEY \`FK_9bf2411e82c38cfd8af4f4c6419\``);
        await queryRunner.query(`ALTER TABLE \`hosted_game\` DROP FOREIGN KEY \`FK_b1e0077ad74acda2ff6850016db\``);
        await queryRunner.query(`ALTER TABLE \`hosted_game\` DROP FOREIGN KEY \`FK_8485625a8b08f4e466a677c0ff1\``);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` DROP FOREIGN KEY \`FK_4e69882dfa491440fd16f8de41d\``);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` DROP FOREIGN KEY \`FK_dadc0fbc5a781e12238d18c2bf5\``);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` DROP FOREIGN KEY \`FK_c274da5202ba2bfed1b709bd91b\``);
        await queryRunner.query(`ALTER TABLE \`tournament_match\` DROP FOREIGN KEY \`FK_798f3a43f03fef1d3b716b49cbf\``);
        await queryRunner.query(`ALTER TABLE \`tournament\` DROP FOREIGN KEY \`FK_9ddfd4f20c2d0fd731bbd681ae7\``);
        await queryRunner.query(`ALTER TABLE \`tournament_admin\` DROP FOREIGN KEY \`FK_a3fafe30c4529ae594db838c194\``);
        await queryRunner.query(`ALTER TABLE \`tournament_admin\` DROP FOREIGN KEY \`FK_cb6125b61aa3cf2fd9176cab63f\``);
        await queryRunner.query(`ALTER TABLE \`tournament_history\` DROP FOREIGN KEY \`FK_5260cc7b38cb3dcf6cd1599a038\``);
        await queryRunner.query(`ALTER TABLE \`tournament_subscription\` DROP FOREIGN KEY \`FK_740a292db70568125e804ec81fe\``);
        await queryRunner.query(`ALTER TABLE \`tournament_subscription\` DROP FOREIGN KEY \`FK_24a012d4472711117179de117a3\``);
        await queryRunner.query(`ALTER TABLE \`tournament_participant\` DROP FOREIGN KEY \`FK_dc4bf5986dc2754e8fa6141de1e\``);
        await queryRunner.query(`ALTER TABLE \`tournament_participant\` DROP FOREIGN KEY \`FK_ff34ec6606707ba26db17e16cee\``);
        await queryRunner.query(`ALTER TABLE \`hosted_game_to_player\` DROP FOREIGN KEY \`FK_a8b097c56ee69fdddf730e7cf78\``);
        await queryRunner.query(`ALTER TABLE \`hosted_game_to_player\` DROP FOREIGN KEY \`FK_fdf42b21f9f53fc1591693f3dab\``);
        await queryRunner.query(`ALTER TABLE \`chat_message\` DROP FOREIGN KEY \`FK_c11c5541b19938027069b21ef66\``);
        await queryRunner.query(`ALTER TABLE \`chat_message\` DROP FOREIGN KEY \`FK_066efba3e9ebaaf2a9363b44bef\``);
        await queryRunner.query(`DROP INDEX \`IDX_187aa9ff1431c29528960322b0\` ON \`player_moderation_action_channel_chat_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_32046a0dd10be92520342f800e\` ON \`player_moderation_action_channel_chat_message\``);
        await queryRunner.query(`DROP TABLE \`player_moderation_action_channel_chat_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_2919df3d450d056338c5d86e93\` ON \`player_moderation_action_chat_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_6ea10243a0f603c2e578c15082\` ON \`player_moderation_action_chat_message\``);
        await queryRunner.query(`DROP TABLE \`player_moderation_action_chat_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_8a004a11c3f59b65cb9af2f58e\` ON \`rating_games_hosted_game\``);
        await queryRunner.query(`DROP INDEX \`IDX_870f3e487e4342542fe7f959d2\` ON \`rating_games_hosted_game\``);
        await queryRunner.query(`DROP TABLE \`rating_games_hosted_game\``);
        await queryRunner.query(`DROP TABLE \`tournament_banned_player\``);
        await queryRunner.query(`DROP TABLE \`player_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_7c969e1d02d0de0392f3562e29\` ON \`player_push_subscription\``);
        await queryRunner.query(`DROP INDEX \`IDX_c3540736ec9e18b0921ff57663\` ON \`player_push_subscription\``);
        await queryRunner.query(`DROP TABLE \`player_push_subscription\``);
        await queryRunner.query(`DROP INDEX \`IDX_0e4299931e18a9f324a4f87b3f\` ON \`player_notification\``);
        await queryRunner.query(`DROP TABLE \`player_notification\``);
        await queryRunner.query(`DROP INDEX \`IDX_733a724427bf9b9b24d43e1539\` ON \`player_moderation_action\``);
        await queryRunner.query(`DROP TABLE \`player_moderation_action\``);
        await queryRunner.query(`DROP TABLE \`game_analyze\``);
        await queryRunner.query(`DROP TABLE \`conditional_moves\``);
        await queryRunner.query(`DROP INDEX \`IDX_800e6da7e4c30fbb0653ba7bb6\` ON \`channel\``);
        await queryRunner.query(`DROP TABLE \`channel\``);
        await queryRunner.query(`DROP INDEX \`IDX_304b2f9ce4b54361694f08e939\` ON \`channel_chat_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_e1f0bf78f736fd2d332252fb32\` ON \`channel_chat_message\``);
        await queryRunner.query(`DROP TABLE \`channel_chat_message\``);
        await queryRunner.query(`DROP TABLE \`ai_config\``);
        await queryRunner.query(`DROP INDEX \`REL_4ad11722d1a822cb14f277340d\` ON \`player\``);
        await queryRunner.query(`DROP INDEX \`IDX_fd3768c309e99f68d3a1cbadc7\` ON \`player\``);
        await queryRunner.query(`DROP INDEX \`IDX_a457ce2bf3dff68e40d8ed0ea8\` ON \`player\``);
        await queryRunner.query(`DROP INDEX \`IDX_6ee4bd7846a1ef85af5f6134ae\` ON \`player\``);
        await queryRunner.query(`DROP INDEX \`IDX_241146be1657c624807b4cf869\` ON \`player\``);
        await queryRunner.query(`DROP INDEX \`IDX_0e28654c29f71f06b98759dada\` ON \`player\``);
        await queryRunner.query(`DROP TABLE \`player\``);
        await queryRunner.query(`DROP INDEX \`IDX_b5f6a27c596dd94c726d6fcbb3\` ON \`rating\``);
        await queryRunner.query(`DROP TABLE \`rating\``);
        await queryRunner.query(`DROP INDEX \`REL_9bf2411e82c38cfd8af4f4c641\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`REL_b1e0077ad74acda2ff6850016d\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`IDX_f76de6ed10d8423f5282f4e022\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a3457cfa4a21186667d094da8\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`IDX_0ba44d40b3239783f505eeb25d\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_endedAt\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_endedAt_desc\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_state_endedAt\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_state_endedAt_desc\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_state_opponentType_endedAt\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_state_opponentType_endedAt_desc\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_state_ranked_opponentType_endedAt\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_state_ranked_opponentType_endedAt_desc\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_ranked_opponentType_endedAt\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_ranked_opponentType_endedAt_desc\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_opponentType_endedAt\` ON \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`index_opponentType_endedAt_desc\` ON \`hosted_game\``);
        await queryRunner.query(`DROP TABLE \`hosted_game\``);
        await queryRunner.query(`DROP INDEX \`REL_c274da5202ba2bfed1b709bd91\` ON \`tournament_match\``);
        await queryRunner.query(`DROP INDEX \`IDX_2b9bc4824bb07421f07185f7bc\` ON \`tournament_match\``);
        await queryRunner.query(`DROP TABLE \`tournament_match\``);
        await queryRunner.query(`DROP INDEX \`IDX_698317abb506538c31157f1f8d\` ON \`tournament\``);
        await queryRunner.query(`DROP INDEX \`IDX_4839ffb50981dfa7f67c270b77\` ON \`tournament\``);
        await queryRunner.query(`DROP TABLE \`tournament\``);
        await queryRunner.query(`DROP TABLE \`tournament_admin\``);
        await queryRunner.query(`DROP TABLE \`tournament_history\``);
        await queryRunner.query(`DROP TABLE \`tournament_subscription\``);
        await queryRunner.query(`DROP TABLE \`tournament_participant\``);
        await queryRunner.query(`DROP TABLE \`hosted_game_to_player\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb865ed2d1270259065314ef35\` ON \`chat_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_1494ddf57db06eb4a8fb13d95e\` ON \`chat_message\``);
        await queryRunner.query(`DROP TABLE \`chat_message\``);
    }

}
